import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

type TranslationValue = string | { one: string; other: string };

const translations: Record<Language, Record<string, TranslationValue>> = {
  en: {
    welcome: "Welcome to Benin",
    explore_soul: "Explore the Soul\nof Africa",
    search_placeholder: "Where do you want to go?",
    featured: "Featured Destinations",
    see_all: "See All",
    heritage_sites: "UNESCO Heritage Sites",
    nearby: "Nearby Activities",
    all: "All",
    food: "Food",
    hotels: "Hotels",
    home: "Home",
    map: "Map",
    tours: "Explore",
    bookings: "Bookings",
    profile: "Profile",
    discover_circuits: "Discover Circuits",
    search_tours: "Search trails, history, locations...",
    my_bookings: "My Bookings",
    upcoming: "Upcoming",
    past: "Past",
    guests: "Guests",
    view_ticket: "View Ticket",
    complete_payment: "Complete Payment",
    looking_for_more: "Looking for more?",
    discover_new: "Discover new heritage sites and circuits in Benin.",
    explore_circuits: "Explore Circuits",
    splash_loading: "Loading...",
    splash_text: "Bénin, a world of splendors",
    price_per_person: "Price per person",
    book_visit: "Book Visit",
    about_dest: "About the destination",
    read_more: "Read more",
    reviews: "Reviews",
    location: "Location",
    explore_map: "Explore Map",
    amenities: "Amenities",
    hours: "Hours",
    duration: "Duration",
    entry: "Entry",
    ticketed: "Ticketed",
    nature: "Nature",
    culture: "Culture",
    history: "Heritage",
    voodoo: "Voodoo",
    view_on_map: "View on Map",
    book_for: "Book for",
    stops: "Stops",
    walk: "Walk",
    small_group: "Small Group",
    included_4x4: "4x4 Included",
    contact_price: "Contact for price",
    payment_pending: "Payment Pending",
    confirmed: "Confirmed",
    reviews_count: "reviews",
    ago: "ago",
    weeks: "weeks",
    day: "Day",
    days: "Days",
    welcome_msg: "Welcome to Benin",
    no_results: "No results found",
    try_another: "Try another search term",
    results: { one: "{count} result", other: "{count} results" },
    heritage: "Heritage",
    found: "found",
    discover: "Discover",
    booking_confirmed: "Booking Confirmed",
    booking_confirmed_desc: "Your trip to Ouidah is confirmed for tomorrow.",
    promo_title: "20% Off Tours",
    promo_desc: "Limited time offer for Pendjari Safari.",
    no_bookings: "No bookings found",
    e_ticket: "E-Ticket",
    scan_at_entrance: "Scan at entrance",
    booking_id: "Booking ID",
    download_pdf: "Download PDF",
    booking_success: "Booking confirmed!",
    select_date: "Choose a date",
    select_time: "Choose a time",
    confirm: "Confirm",
    edit_date: "Edit date",
    edit_time: "Edit time",
    choose_time: "Select a time",
    guests_count: "Number of guests",
    confirm_booking: "Confirm booking",
    total: "Total",
    filters_advanced: "Advanced filters",
    price: "Price",
    sort_by: "Sort by",
    rating_label: "Rating",
    apply_filters: "Apply filters",
    no_tours: "No tours found",
    adjust_filters: "Try changing your filters",
    reset_filters: "Reset filters",
    benin_label: "Benin",
    circuits: { one: "{count} tour", other: "{count} tours" },
    places_found: { one: "{count} place found", other: "{count} places found" },
    new_badge: "New badge!",
    account: "Account",
    personal_info: "Personal information",
    payment_methods: "Payment methods",
    payment_methods_desc: "KKiaPay, FedaPay",
    preferences: "Preferences",
    notifications: "Notifications",
    theme_mode: "Theme",
    dark_mode: "Dark",
    light_mode: "Light",
    dark_mode_on: "Luxury theme enabled",
    light_mode_on: "Light theme enabled",
    language_label: "Language",
    services: "Services",
    support: "Support",
    help_faq: "Help & FAQ",
    contact_us: "Contact us",
    logout: "Sign out",
    profile_levels: "Explorer Levels",
    current: "CURRENT",
    unlocked: "Unlocked",
    locked: "Locked",
    badges: { one: "{count} badge unlocked", other: "{count} badges unlocked" },
    badges_title: "My Badges",
    badges_unlocked: "Unlocked ({count})",
    badges_locked: "To unlock ({count})",
    points_title: "My Points",
    points_tip: "Earn points by traveling (+50), reviews (+25), and booking (+100)!",
    history: "History",
    trips_title: "My Trips",
    destinations_visited: { one: "{count} destination visited", other: "{count} destinations visited" },
    reviews_title: "My Reviews",
    reviews_published: { one: "{count} review published", other: "{count} reviews published" },
    leave_review: "Leave a review",
    review_left: "Review submitted",
    people_found_helpful: { one: "{count} person found this helpful", other: "{count} people found this helpful" },
    logout_confirm: "Sign out",
    logout_prompt: "Are you sure you want to sign out?",
    cancel: "Cancel",
    sign_out: "Sign out",
    set_default: "Set default",
    add_method: "Add a method",
    payment_info: "Secure payments via local aggregators: KKiaPay and FedaPay - Mobile Money (MTN, Moov) and cards.",
    default_label: "DEFAULT",
    choose_language: "Choose language",
    trips_label: "Trips",
    reviews_label: "Reviews",
    points_label: "Points",
    level: "Level",
    to_next_level: "{current} / {target} pts to {levelName}",
    by_default: "By default",
    edit: "Edit",
    full_name: "Full name",
    email: "Email",
    phone: "Phone",
    country: "Country",
    evisa_title: "e-Visa application",
    evisa_desc: "Electronic visa for Benin",
    mobile_money_cards: "Mobile Money & Cards",
    mtn_moov_cards: "MTN, Moov, Cards",
    points_unit: "points"
  },
  fr: {
    welcome: "Bienvenue au Bénin",
    explore_soul: "Explorez l'âme\nde l'Afrique",
    search_placeholder: "Où souhaitez-vous aller ?",
    featured: "Destinations en Vedette",
    see_all: "Voir tout",
    heritage_sites: "Sites UNESCO",
    nearby: "Activités à proximité",
    all: "Tout",
    food: "Restauration",
    hotels: "Hôtels",
    home: "Accueil",
    map: "Carte",
    tours: "Explorer",
    bookings: "Réservations",
    profile: "Profil",
    discover_circuits: "Découvrir les Circuits",
    search_tours: "Rechercher pistes, histoire...",
    my_bookings: "Mes Réservations",
    upcoming: "À venir",
    past: "Passé",
    guests: "Invités",
    view_ticket: "Voir le billet",
    complete_payment: "Payer",
    looking_for_more: "Vous en voulez plus ?",
    discover_new: "Découvrez de nouveaux sites et circuits.",
    explore_circuits: "Explorer les Circuits",
    splash_loading: "Chargement...",
    no_results: "Aucun résultat trouvé",
    try_another: "Essayez un autre terme",
    results: { one: "{count} résultat", other: "{count} résultats" },
    heritage: "Patrimoine",
    splash_text: "Bénin, un monde de splendeurs",
    price_per_person: "Prix par personne",
    book_visit: "Réserver",
    about_dest: "À propos",
    read_more: "Lire plus",
    reviews: "Avis",
    location: "Lieu",
    explore_map: "Explorer la carte",
    amenities: "Commodités",
    hours: "Horaires",
    duration: "Durée",
    entry: "Entrée",
    ticketed: "Billet requis",
    nature: "Nature",
    culture: "Culture",
    history: "Patrimoine",
    voodoo: "Vaudou",
    view_on_map: "Voir sur la carte",
    book_for: "Réserver pour",
    stops: "Arrêts",
    walk: "Marche",
    small_group: "Petit Groupe",
    included_4x4: "4x4 Inclus",
    contact_price: "Contactez-nous",
    payment_pending: "En attente",
    confirmed: "Confirmé",
    reviews_count: "avis",
    ago: "il y a",
    weeks: "semaines",
    day: "Jour",
    days: "Jours",
    welcome_msg: "Bienvenue au Bénin",
    found: "trouvé(s)",
    discover: "Découvrir",
    booking_confirmed: "Réservation confirmée",
    booking_confirmed_desc: "Votre voyage à Ouidah est confirmé pour demain.",
    promo_title: "20% de réduction",
    promo_desc: "Offre limitée pour le safari de la Pendjari.",
    no_bookings: "Aucune réservation trouvée",
    e_ticket: "E-Ticket",
    scan_at_entrance: "Scannez à l'entrée",
    booking_id: "ID de réservation",
    download_pdf: "Télécharger PDF",
    booking_success: "Réservation confirmée !",
    select_date: "Choisir une date",
    select_time: "Choisir un horaire",
    confirm: "Confirmer",
    edit_date: "Modifier la date",
    edit_time: "Modifier l'horaire",
    choose_time: "Choisissez un horaire",
    guests_count: "Nombre de personnes",
    confirm_booking: "Confirmer la réservation",
    total: "Total",
    filters_advanced: "Filtres avancés",
    price: "Prix",
    sort_by: "Trier par",
    rating_label: "Note",
    apply_filters: "Appliquer les filtres",
    no_tours: "Aucun circuit trouvé",
    adjust_filters: "Essayez de modifier vos filtres",
    reset_filters: "Réinitialiser les filtres",
    benin_label: "Bénin",
    circuits: { one: "{count} circuit", other: "{count} circuits" },
    places_found: { one: "{count} lieu trouvé", other: "{count} lieux trouvés" },
    new_badge: "Nouveau badge !",
    account: "Compte",
    personal_info: "Informations personnelles",
    payment_methods: "Méthodes de paiement",
    payment_methods_desc: "KKiaPay, FedaPay",
    preferences: "Préférences",
    notifications: "Notifications",
    theme_mode: "Mode",
    dark_mode: "Sombre",
    light_mode: "Clair",
    dark_mode_on: "Thème luxueux activé",
    light_mode_on: "Thème clair activé",
    language_label: "Langue",
    services: "Services",
    support: "Support",
    help_faq: "Aide & FAQ",
    contact_us: "Nous contacter",
    logout: "Déconnexion",
    profile_levels: "Niveaux Explorer",
    current: "ACTUEL",
    unlocked: "Débloqués",
    locked: "À débloquer",
    badges: { one: "{count} badge débloqué", other: "{count} badges débloqués" },
    badges_title: "Mes Badges",
    badges_unlocked: "Débloqués ({count})",
    badges_locked: "À débloquer ({count})",
    points_title: "Mes Points",
    points_tip: "Gagnez des points en voyageant (+50), en laissant des avis (+25) et en réservant (+100) !",
    history: "Historique",
    trips_title: "Mes Voyages",
    destinations_visited: { one: "{count} destination visitée", other: "{count} destinations visitées" },
    reviews_title: "Mes Avis",
    reviews_published: { one: "{count} avis publié", other: "{count} avis publiés" },
    leave_review: "Laisser un avis",
    review_left: "Avis laissé",
    people_found_helpful: { one: "{count} personne a trouvé cet avis utile", other: "{count} personnes ont trouvé cet avis utile" },
    logout_confirm: "Déconnexion",
    logout_prompt: "Êtes-vous sûr de vouloir vous déconnecter ?",
    cancel: "Annuler",
    sign_out: "Déconnecter",
    set_default: "Définir par défaut",
    add_method: "Ajouter une méthode",
    payment_info: "Paiements sécurisés via des agrégateurs locaux : KKiaPay et FedaPay - Mobile Money (MTN, Moov) et cartes bancaires.",
    default_label: "PAR DÉFAUT",
    choose_language: "Choisir la langue",
    trips_label: "Voyages",
    reviews_label: "Avis",
    points_label: "Points",
    level: "Niveau",
    to_next_level: "{current} / {target} pts vers {levelName}",
    by_default: "Par défaut",
    edit: "Modifier",
    full_name: "Nom complet",
    email: "Email",
    phone: "Téléphone",
    country: "Pays",
    evisa_title: "Demande de e-Visa",
    evisa_desc: "Visa électronique pour le Bénin",
    mobile_money_cards: "Mobile Money & Cartes",
    mtn_moov_cards: "MTN, Moov, Cartes",
    points_unit: "points"
  }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'gobenin-language';

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    const saved = localStorage.getItem(STORAGE_KEY) as Language | null;
    if (saved === 'en' || saved === 'fr') return saved;
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('fr') ? 'fr' : 'en';
  });

  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem(STORAGE_KEY, language);
    }
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>) => {
    const entry = translations[language][key];
    if (!entry) return key;
    const text = typeof entry === 'string'
      ? entry
      : (params?.count === 1 ? entry.one : entry.other);
    if (!params) return text;
    return Object.entries(params).reduce((acc, [paramKey, value]) => {
      return acc.replaceAll(`{${paramKey}}`, String(value));
    }, text);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
