import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

type TranslationValue = string | { one: string; other: string };
const warnedMissingKeys = new Set<string>();

export const translations: Record<Language, Record<string, TranslationValue>> = {
  en: {
    welcome: "Welcome to Benin",
    explore_soul: "Explore the Soul\nof Africa",
    search_placeholder: "Where do you want to go?",
    featured: "Featured Destinations",
    see_all: "See All",
    heritage_sites: "UNESCO Heritage Sites",
    nearby: "Nearby Activities",
    all: "All",
    food: "Food",
    hotels: "Hotels",
    home: "Home",
    map: "Map",
    tours: "Explore",
    bookings: "Bookings",
    profile: "Profile",
    discover_circuits: "Discover Circuits",
    search_tours: "Search trails, history, locations...",
    my_bookings: "My Bookings",
    upcoming: "Upcoming",
    past: "Past",
    guests: "Guests",
    view_ticket: "View Ticket",
    complete_payment: "Complete Payment",
    looking_for_more: "Looking for more?",
    discover_new: "Discover new heritage sites and circuits in Benin.",
    explore_circuits: "Explore Circuits",
    splash_loading: "Loading...",
    splash_text: "Bénin, a world of splendors",
    price_per_person: "Price per person",
    book_visit: "Book Visit",
    about_dest: "About the destination",
    read_more: "Read more",
    reviews: "Reviews",
    location: "Location",
    explore_map: "Explore Map",
    amenities: "Amenities",
    hours: "Hours",
    duration: "Duration",
    entry: "Entry",
    ticketed: "Ticketed",
    nature: "Nature",
    culture: "Culture",
    history: "Heritage",
    relaxation: "Relaxation",
    hotel: "Hotel",
    cultural: "Cultural",
    vodun: "Vodun",
    view_on_map: "View on Map",
    book_for: "Book for",
    stops: "Stops",
    walk: "Walk",
    small_group: "Small Group",
    included_4x4: "4x4 Included",
    contact_price: "Contact for price",
    payment_pending: "Payment Pending",
    confirmed: "Confirmed",
    reviews_count: "reviews",
    ago: "ago",
    weeks: "weeks",
    day: "Day",
    days: "Days",
    welcome_msg: "Welcome to Benin",
    no_results: "No results found",
    try_another: "Try another search term",
    results: { one: "{count} result", other: "{count} results" },
    heritage: "Heritage",
    found: "found",
    discover: "Discover",
    booking_confirmed: "Booking Confirmed",
    booking_confirmed_desc: "Your trip to Ouidah is confirmed for tomorrow.",
    promo_title: "20% Off Tours",
    promo_desc: "Limited time offer for Pendjari Safari.",
    no_bookings: "No bookings found",
    e_ticket: "E-Ticket",
    scan_at_entrance: "Scan at entrance",
    booking_id: "Booking ID",
    download_pdf: "Download PDF",
    booking_success: "Booking confirmed!",
    select_date: "Choose a date",
    select_time: "Choose a time",
    confirm: "Confirm",
    edit_date: "Edit date",
    edit_time: "Edit time",
    choose_time: "Select a time",
    guests_count: "Number of guests",
    guests_people: { one: "{count} guest", other: "{count} guests" },
    confirm_booking: "Confirm booking",
    total: "Total",
    filters_advanced: "Advanced filters",
    price: "Price",
    sort_by: "Sort by",
    rating_label: "Rating",
    apply_filters: "Apply filters",
    no_tours: "No tours found",
    adjust_filters: "Try changing your filters",
    reset_filters: "Reset filters",
    benin_label: "Benin",
    circuits: { one: "{count} tour", other: "{count} tours" },
    places_found: { one: "{count} place found", other: "{count} places found" },
    new_badge: "New badge!",
    account: "Account",
    personal_info: "Personal information",
    payment_methods: "Payment methods",
    payment_methods_desc: "KKiaPay, FedaPay",
    preferences: "Preferences",
    notifications: "Notifications",
    theme_mode: "Theme",
    dark_mode: "Dark",
    light_mode: "Light",
    dark_mode_on: "Luxury theme enabled",
    light_mode_on: "Light theme enabled",
    language_label: "Language",
    services: "Services",
    support: "Support",
    help_faq: "Help & FAQ",
    contact_us: "Contact us",
    logout: "Sign out",
    profile_levels: "Explorer Levels",
    current: "CURRENT",
    unlocked: "Unlocked",
    locked: "Locked",
    badges: { one: "{count} badge unlocked", other: "{count} badges unlocked" },
    badges_title: "My Badges",
    badges_unlocked: "Unlocked ({count})",
    badges_locked: "To unlock ({count})",
    points_title: "My Points",
    points_tip: "Earn points by traveling (+50), reviews (+25), and booking (+100)!",
    points_history: "History",
    trips_title: "My Trips",
    destinations_visited: { one: "{count} destination visited", other: "{count} destinations visited" },
    reviews_title: "My Reviews",
    reviews_published: { one: "{count} review published", other: "{count} reviews published" },
    leave_review: "Leave a review",
    review_left: "Review submitted",
    people_found_helpful: { one: "{count} person found this helpful", other: "{count} people found this helpful" },
    logout_confirm: "Sign out",
    logout_prompt: "Are you sure you want to sign out?",
    cancel: "Cancel",
    sign_out: "Sign out",
    set_default: "Set default",
    add_method: "Add a method",
    payment_info: "Secure payments via local aggregators: KKiaPay and FedaPay - Mobile Money (MTN, Moov) and cards.",
    default_label: "DEFAULT",
    choose_language: "Choose language",
    trips_label: "Trips",
    reviews_label: "Reviews",
    points_label: "Points",
    level: "Level",
    to_next_level: "{current} / {target} pts to {levelName}",
    by_default: "By default",
    edit: "Edit",
    full_name: "Full name",
    email: "Email",
    phone: "Phone",
    country: "Country",
    evisa_title: "e-Visa application",
    evisa_desc: "Electronic visa for Benin",
    mobile_money_cards: "Mobile Money & Cards",
    mtn_moov_cards: "MTN, Moov, Cards",
    points_unit: "points",
    hero_video_title: "Discover Benin",
    default_trip_1_name: "Royal Palaces of Abomey",
    default_trip_1_location: "Abomey",
    default_trip_2_name: "Pendjari Park",
    default_trip_2_location: "Natitingou",
    default_trip_3_name: "Ouidah",
    default_trip_3_location: "Ouidah",
    default_review_1_comment: "Incredible historical experience!",
    default_review_2_comment: "Magnificent safari, wildlife was there!",
    auth_login_title: "Sign in",
    auth_signup_title: "Create account",
    auth_forgot_title: "Forgot password",
    auth_login_sub: "Welcome to GoBenin",
    auth_signup_sub: "Join the community",
    auth_forgot_sub: "Reset your password",
    auth_name_label: "Name",
    auth_email_label: "Email",
    auth_password_label: "Password",
    auth_name_placeholder: "Your name",
    auth_email_placeholder: "you@email.com",
    auth_password_placeholder: "••••••••",
    auth_signin: "Sign in",
    auth_signup: "Sign up",
    auth_send_link: "Send link",
    auth_or: "or",
    auth_google: "Continue with Google",
    auth_forgot_link: "Forgot password?",
    auth_no_account: "No account?",
    auth_signup_link: "Sign up",
    auth_have_account: "Already have an account?",
    auth_login_link: "Sign in",
    auth_back_login: "Back to sign in",
    auth_error_generic: "Something went wrong",
    auth_success_confirm_email: "Check your email to confirm your account",
    auth_success_reset: "Password reset email sent",
    auth_google_error: "Google sign-in error",
    about_tour: "About this tour",
    itinerary: "Itinerary",
    stop: "Stop",
    whats_included: "What's included",
    guided_tour: "Guided tour",
    photo_ops: "Photo opportunities",
    refreshments: "Refreshments",
    audio_guide: "Audio guide",
    choose_banner: "Choose banner color",
    review_author: "Sarah Jenkins",
    review_quote: "An incredible walk through history. The guides are very knowledgeable about the Dahomey Amazon warriors. Highly recommend!",
    back: "Back",
    book_now: "Book now",
    points_reason_trip: "Trip - {name}",
    points_reason_review: "Review for {name}",
    points_reason_booking: "Booking - {name}",
    points_reason_welcome: "Welcome bonus",
    points_reason_premium: "Premium booking",
    level_1_name: "Beginner",
    level_2_name: "Adventurer",
    level_3_name: "Explorer",
    level_4_name: "Pioneer",
    level_5_name: "Legend",
    level_1_benefit_1: "Access to basic tours",
    level_2_benefit_1: "5% discount",
    level_2_benefit_2: "Priority access",
    level_3_benefit_1: "10% discount",
    level_3_benefit_2: "Exclusive guides",
    level_4_benefit_1: "15% discount",
    level_4_benefit_2: "VIP experiences",
    level_5_benefit_1: "20% discount",
    level_5_benefit_2: "Unlimited access",
    level_5_benefit_3: "Concierge",
    badge_first_trip_name: "First step",
    badge_first_trip_desc: "Complete your first trip",
    badge_explorer_5_name: "Explorer",
    badge_explorer_5_desc: "Visit 5 destinations",
    badge_globe_trotter_name: "Globetrotter",
    badge_globe_trotter_desc: "Visit 10 destinations",
    badge_first_review_name: "Critic",
    badge_first_review_desc: "Write your first review",
    badge_reviewer_10_name: "Influencer",
    badge_reviewer_10_desc: "Write 10 reviews",
    badge_reviewer_25_name: "Local Expert",
    badge_reviewer_25_desc: "Write 25 reviews",
    badge_points_500_name: "Collector",
    badge_points_500_desc: "Earn 500 points",
    badge_points_1000_name: "Treasurer",
    badge_points_1000_desc: "Earn 1000 points",
    badge_benin_lover_name: "Benin lover",
    badge_benin_lover_desc: "Special badge for fans",
    load_error: "Unable to load data",
    search_error: "Search error"
  },
  fr: {
    welcome: "Bienvenue au Bénin",
    explore_soul: "Explorez l'âme\nde l'Afrique",
    search_placeholder: "Où souhaitez-vous aller ?",
    featured: "Destinations en Vedette",
    see_all: "Voir tout",
    heritage_sites: "Sites UNESCO",
    nearby: "Activités à proximité",
    all: "Tout",
    food: "Restauration",
    hotels: "Hôtels",
    home: "Accueil",
    map: "Carte",
    tours: "Explorer",
    bookings: "Réservations",
    profile: "Profil",
    discover_circuits: "Découvrir les Circuits",
    search_tours: "Rechercher pistes, histoire...",
    my_bookings: "Mes Réservations",
    upcoming: "À venir",
    past: "Passé",
    guests: "Invités",
    view_ticket: "Voir le billet",
    complete_payment: "Payer",
    looking_for_more: "Vous en voulez plus ?",
    discover_new: "Découvrez de nouveaux sites et circuits.",
    explore_circuits: "Explorer les Circuits",
    splash_loading: "Chargement...",
    no_results: "Aucun résultat trouvé",
    try_another: "Essayez un autre terme",
    results: { one: "{count} résultat", other: "{count} résultats" },
    heritage: "Patrimoine",
    splash_text: "Bénin, un monde de splendeurs",
    price_per_person: "Prix par personne",
    book_visit: "Réserver",
    about_dest: "À propos",
    read_more: "Lire plus",
    reviews: "Avis",
    location: "Lieu",
    explore_map: "Explorer la carte",
    amenities: "Commodités",
    hours: "Horaires",
    duration: "Durée",
    entry: "Entrée",
    ticketed: "Billet requis",
    nature: "Nature",
    culture: "Culture",
    history: "Patrimoine",
    relaxation: "Détente",
    hotel: "Hôtel",
    cultural: "Culturel",
    vodun: "Vodun",
    view_on_map: "Voir sur la carte",
    book_for: "Réserver pour",
    stops: "Arrêts",
    walk: "Marche",
    small_group: "Petit Groupe",
    included_4x4: "4x4 Inclus",
    contact_price: "Contactez-nous",
    payment_pending: "En attente",
    confirmed: "Confirmé",
    reviews_count: "avis",
    ago: "il y a",
    weeks: "semaines",
    day: "Jour",
    days: "Jours",
    welcome_msg: "Bienvenue au Bénin",
    found: "trouvé(s)",
    discover: "Découvrir",
    booking_confirmed: "Réservation confirmée",
    booking_confirmed_desc: "Votre voyage à Ouidah est confirmé pour demain.",
    promo_title: "20% de réduction",
    promo_desc: "Offre limitée pour le safari de la Pendjari.",
    no_bookings: "Aucune réservation trouvée",
    e_ticket: "E-Ticket",
    scan_at_entrance: "Scannez à l'entrée",
    booking_id: "ID de réservation",
    download_pdf: "Télécharger PDF",
    booking_success: "Réservation confirmée !",
    select_date: "Choisir une date",
    select_time: "Choisir un horaire",
    confirm: "Confirmer",
    edit_date: "Modifier la date",
    edit_time: "Modifier l'horaire",
    choose_time: "Choisissez un horaire",
    guests_count: "Nombre de personnes",
    guests_people: { one: "{count} personne", other: "{count} personnes" },
    confirm_booking: "Confirmer la réservation",
    total: "Total",
    filters_advanced: "Filtres avancés",
    price: "Prix",
    sort_by: "Trier par",
    rating_label: "Note",
    apply_filters: "Appliquer les filtres",
    no_tours: "Aucun circuit trouvé",
    adjust_filters: "Essayez de modifier vos filtres",
    reset_filters: "Réinitialiser les filtres",
    benin_label: "Bénin",
    circuits: { one: "{count} circuit", other: "{count} circuits" },
    places_found: { one: "{count} lieu trouvé", other: "{count} lieux trouvés" },
    new_badge: "Nouveau badge !",
    account: "Compte",
    personal_info: "Informations personnelles",
    payment_methods: "Méthodes de paiement",
    payment_methods_desc: "KKiaPay, FedaPay",
    preferences: "Préférences",
    notifications: "Notifications",
    theme_mode: "Mode",
    dark_mode: "Sombre",
    light_mode: "Clair",
    dark_mode_on: "Thème luxueux activé",
    light_mode_on: "Thème clair activé",
    language_label: "Langue",
    services: "Services",
    support: "Support",
    help_faq: "Aide & FAQ",
    contact_us: "Nous contacter",
    logout: "Déconnexion",
    profile_levels: "Niveaux Explorer",
    current: "ACTUEL",
    unlocked: "Débloqués",
    locked: "À débloquer",
    badges: { one: "{count} badge débloqué", other: "{count} badges débloqués" },
    badges_title: "Mes Badges",
    badges_unlocked: "Débloqués ({count})",
    badges_locked: "À débloquer ({count})",
    points_title: "Mes Points",
    points_tip: "Gagnez des points en voyageant (+50), en laissant des avis (+25) et en réservant (+100) !",
    points_history: "Historique",
    trips_title: "Mes Voyages",
    destinations_visited: { one: "{count} destination visitée", other: "{count} destinations visitées" },
    reviews_title: "Mes Avis",
    reviews_published: { one: "{count} avis publié", other: "{count} avis publiés" },
    leave_review: "Laisser un avis",
    review_left: "Avis laissé",
    people_found_helpful: { one: "{count} personne a trouvé cet avis utile", other: "{count} personnes ont trouvé cet avis utile" },
    logout_confirm: "Déconnexion",
    logout_prompt: "Êtes-vous sûr de vouloir vous déconnecter ?",
    cancel: "Annuler",
    sign_out: "Déconnecter",
    set_default: "Définir par défaut",
    add_method: "Ajouter une méthode",
    payment_info: "Paiements sécurisés via des agrégateurs locaux : KKiaPay et FedaPay - Mobile Money (MTN, Moov) et cartes bancaires.",
    default_label: "PAR DÉFAUT",
    choose_language: "Choisir la langue",
    trips_label: "Voyages",
    reviews_label: "Avis",
    points_label: "Points",
    level: "Niveau",
    to_next_level: "{current} / {target} pts vers {levelName}",
    by_default: "Par défaut",
    edit: "Modifier",
    full_name: "Nom complet",
    email: "Email",
    phone: "Téléphone",
    country: "Pays",
    evisa_title: "Demande de e-Visa",
    evisa_desc: "Visa électronique pour le Bénin",
    mobile_money_cards: "Mobile Money & Cartes",
    mtn_moov_cards: "MTN, Moov, Cartes",
    points_unit: "points",
    hero_video_title: "Découvrez le Bénin",
    default_trip_1_name: "Palais Royaux d'Abomey",
    default_trip_1_location: "Abomey",
    default_trip_2_name: "Parc Pendjari",
    default_trip_2_location: "Natitingou",
    default_trip_3_name: "Ouidah",
    default_trip_3_location: "Ouidah",
    default_review_1_comment: "Incroyable expérience historique!",
    default_review_2_comment: "Safari magnifique, animaux sauvages au rendez-vous!",
    auth_login_title: "Connexion",
    auth_signup_title: "Créer un compte",
    auth_forgot_title: "Mot de passe oublié",
    auth_login_sub: "Bienvenue sur GoBénin",
    auth_signup_sub: "Rejoignez la communauté",
    auth_forgot_sub: "Réinitialisez votre mot de passe",
    auth_name_label: "Nom",
    auth_email_label: "Email",
    auth_password_label: "Mot de passe",
    auth_name_placeholder: "Votre nom",
    auth_email_placeholder: "vous@email.com",
    auth_password_placeholder: "••••••••",
    auth_signin: "Se connecter",
    auth_signup: "S'inscrire",
    auth_send_link: "Envoyer le lien",
    auth_or: "ou",
    auth_google: "Continuer avec Google",
    auth_forgot_link: "Mot de passe oublié ?",
    auth_no_account: "Pas de compte ?",
    auth_signup_link: "Inscrivez-vous",
    auth_have_account: "Déjà un compte ?",
    auth_login_link: "Connectez-vous",
    auth_back_login: "Retour à la connexion",
    auth_error_generic: "Une erreur est survenue",
    auth_success_confirm_email: "Vérifiez votre email pour confirmer votre compte",
    auth_success_reset: "Email de réinitialisation envoyé",
    auth_google_error: "Erreur de connexion Google",
    about_tour: "À propos de ce circuit",
    itinerary: "Itinéraire",
    stop: "Étape",
    whats_included: "Ce qui est inclus",
    guided_tour: "Visite guidée",
    photo_ops: "Opportunités photos",
    refreshments: "Rafraîchissements",
    audio_guide: "Audioguide",
    review_author: "Sarah Jenkins",
    review_quote: "Une marche incroyable à travers l'histoire. Les guides connaissent très bien les Amazones du Dahomey. Je recommande !",
    back: "Retour",
    book_now: "Réserver",
    choose_banner: "Choisir la couleur de bannière",
    points_reason_trip: "Voyage - {name}",
    points_reason_review: "Avis sur {name}",
    points_reason_booking: "Réservation - {name}",
    points_reason_welcome: "Bonus de bienvenue",
    points_reason_premium: "Réservation premium",
    level_1_name: "Débutant",
    level_2_name: "Aventurier",
    level_3_name: "Explorateur",
    level_4_name: "Pionnier",
    level_5_name: "Légende",
    level_1_benefit_1: "Accès aux circuits de base",
    level_2_benefit_1: "5% de réduction",
    level_2_benefit_2: "Accès prioritaire",
    level_3_benefit_1: "10% de réduction",
    level_3_benefit_2: "Guides exclusifs",
    level_4_benefit_1: "15% de réduction",
    level_4_benefit_2: "Expériences VIP",
    level_5_benefit_1: "20% de réduction",
    level_5_benefit_2: "Accès illimité",
    level_5_benefit_3: "Conciergerie",
    badge_first_trip_name: "Premier Pas",
    badge_first_trip_desc: "Effectuer votre premier voyage",
    badge_explorer_5_name: "Explorateur",
    badge_explorer_5_desc: "Visiter 5 destinations",
    badge_globe_trotter_name: "Globe-Trotter",
    badge_globe_trotter_desc: "Visiter 10 destinations",
    badge_first_review_name: "Critique",
    badge_first_review_desc: "Écrire votre premier avis",
    badge_reviewer_10_name: "Influenceur",
    badge_reviewer_10_desc: "Écrire 10 avis",
    badge_reviewer_25_name: "Expert Local",
    badge_reviewer_25_desc: "Écrire 25 avis",
    badge_points_500_name: "Collectionneur",
    badge_points_500_desc: "Accumuler 500 points",
    badge_points_1000_name: "Trésorier",
    badge_points_1000_desc: "Accumuler 1000 points",
    badge_benin_lover_name: "Amoureux du Bénin",
    badge_benin_lover_desc: "Badge spécial pour les passionnés",
    load_error: "Erreur de chargement",
    search_error: "Erreur de recherche"
  }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'gobenin-language';

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    const saved = localStorage.getItem(STORAGE_KEY) as Language | null;
    if (saved === 'en' || saved === 'fr') return saved;
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('fr') ? 'fr' : 'en';
  });

  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem(STORAGE_KEY, language);
    }
  }, [language]);

  const pluralRules = React.useMemo(() => {
    const locale = language === 'fr' ? 'fr-FR' : 'en-US';
    return new Intl.PluralRules(locale);
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>) => {
    const entry = translations[language][key];
    if (!entry) {
      if (import.meta.env.DEV && !warnedMissingKeys.has(key)) {
        warnedMissingKeys.add(key);
        console.warn(`[i18n] Missing key: ${key}`);
      }
      return key;
    }
    const text = typeof entry === 'string'
      ? entry
      : (() => {
          const count = typeof params?.count === 'number' ? params.count : 0;
          const rule = pluralRules.select(count);
          return entry[rule as 'one' | 'other'] || entry.other;
        })();
    if (!params) return text;
    return Object.entries(params).reduce((acc, [paramKey, value]) => {
      return acc.replaceAll(`{${paramKey}}`, String(value));
    }, text);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
