-- =============================================
-- GoBénin Seed Data
-- =============================================

-- Destinations Featured
INSERT INTO destinations (id, name_en, name_fr, subtitle_en, subtitle_fr, description_en, description_fr, rating, reviews_count, image, category, type) VALUES
('ouidah', 'Ouidah', 'Ouidah', 'Cultural Capital & History', 'Capitale Culturelle & Histoire', 'Discover the rich history of the Slave Route and the Python Temple.', 'Découvrez la riche histoire de la Route des Esclaves et du Temple des Pythons.', 4.8, 320, 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3BkXgR_L3ed9xOwrgBAV5m2Aitw7Tz0CHUWS05-rlFIBM77fPONvZ1hnSgBe48pjiv2_FTAxWEhv-muGaK70KexZZbW0uvKIrV8ljxJNFS7d3Xjp9FiR50pULWiMWaDp81W6Y7niaOoWUEUvgDGo4HP6eI5Kx3YHos-_ovXU8-qf0Pe8Sierr9ldc6PoDU_1vj4XK_z_RhqpDDNrwfd3w76Eku_UZaHeKxTsr_CJ8t_7UFR1OfFdsYh1yy3Ycplw0KlyelcCdXbQ', 'Heritage', 'featured'),

('grand-popo', 'Grand-Popo', 'Grand-Popo', 'Beach & Relaxation', 'Plage & Détente', 'Serene beaches and colonial architecture.', 'Plages sereines et architecture coloniale.', 4.7, 210, 'https://lh3.googleusercontent.com/aida-public/AB6AXuAg8hSUPvJecRMmZFFQwxj9CjWh2uxxGmTyLDq9xMGao2PEEeLBZsOM8dCVsGKIE7fxWNZou3VUvVA6dqbBO0mG_LFhOBA05AxRYXZBPa0VRDHBCx03RAaTy2nI4OEjFQwKTupmkqSC_ZaHOjz_cL5O88RUKijtxkgsJM8aM6xNSlSDGSvy-Rzb7XkzdnJzNSS7pJ401BL-Hn_Wq8Ms0bHOcptYPBFyItWmGipOj0e6fzm9Vx6JWt6en5XkLiGDxVbEpZX28Tow2J0', 'Relaxation', 'featured'),

('ganvie', 'Ganvie', 'Ganvié', 'The Venice of Africa', 'La Venise de l''Afrique', 'A unique lake village built entirely on stilts.', 'Un village lacustre unique entièrement construit sur pilotis.', 4.6, 540, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKYXTj2nacDb7jox30RqEl9DpVxskJXmolFWtve9kSng_tU514bIHwTHffC-l2PcSJda0HN2_OENzUOcdeB-j16qGoBgAl8dskuK7zvcAuoFd8VLpgZaek_uDuCEg6HSJW7ynjGWhz-UoiZUE4riDEJKzT9tklYsmR_mLCuxAsiDZLQwoEUW5isdxxRbpLeOvQkyRnlWo3qxjOKyfe9CueArQwnuDU8zGHV21UeaoQaIMRtgXv7DtFAb-rC_v2mrsuFQqO652mapw', 'Culture', 'featured');

-- Destinations Heritage
INSERT INTO destinations (id, name_en, name_fr, subtitle_en, subtitle_fr, description_en, description_fr, rating, reviews_count, image, category, type, price, hours, duration, images) VALUES
('royal-palaces', 'Royal Palaces', 'Palais Royaux', 'Abomey', 'Abomey', 'The Royal Palaces of Abomey are the major material testimony to the Kingdom of Dahomey which developed from the mid-17th century. Founded in 1625 by the Fon people, the kingdom became a powerful military and commercial empire.', 'Les Palais Royaux d''Abomey sont le principal témoignage matériel du Royaume du Dahomey qui s''est développé à partir du milieu du XVIIe siècle. Fondé en 1625 par le peuple Fon, le royaume est devenu un puissant empire militaire et commercial.', 4.8, 124, 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgFVzBhtc_W5MfJulzowEjdsYqH8v0L61XtoHTWxrV67Bej4KjrCF1QveYTup1Dut8rJzJgcwBhIrrmS60owscvkdPx5K38PeRLSHlJ3dximT3rfwkrSL9vM8NytlK0fEVFecpVkuRDEGrewmZR0Fn4PoaZ6kcvQ6Pu4e9iXanUV1HGnHanMvnAoZrWcC2pCC2eSr3ed1twnmuLriRp51SLMp3Vhq2kKst61x36siZMYOFCDf0O1Yn199MzNIVTD2LVTUJ4vDXP6Y', 'Heritage', 'heritage', '2,500 CFA', '09:00 - 18:00', '2 - 3 Hrs', '["https://lh3.googleusercontent.com/aida-public/AB6AXuC2mw7lkILzKgHvVUKG37_4IfsDR4UGxuPIYYWfnZy_lEmrnN73hT4eHmLPFUibU63jovzesMrG1rc78mb5P8l3V1bbXEhrr_qJCxzUp4pkzzZKGYkKv7VpHAU5Z3tAmUFL7JrMl8QjKXPpsFBXndCQDRR_g1mOtmQDHNQh3YrdBc2Aub1IHtc-su5NesHs_ZkDorBkMUY4rYfCH4iTRcH3-RnKxAIOA9Pxoop98IdV_SBDGBROvk375BTllzdQp0nepethef7MfHU"]'),

('pendjari', 'W-Arly-Pendjari', 'W-Arly-Pendjari', 'North Benin', 'Nord Bénin', 'Experience the heart of West African wildlife in our sustainable eco-lodges. Built with traditional materials, our lodge offers a luxurious yet authentic immersion into nature.', 'Vivez le cœur de la faune ouest-africaine dans nos éco-lodges durables. Construit avec des matériaux traditionnels, notre lodge offre une immersion luxueuse et authentique dans la nature.', 4.9, 89, 'https://lh3.googleusercontent.com/aida-public/AB6AXuAc-zljECU8wk6Dc__smmcNslxEqd1CfOpILozLcALV1Sfdoe5QQw209gVKTInlpNThn4DkDDmPOuwcBgNjTkLBygrZYXn4cefHpm-vNHpbluJNzDTUWRXFY94r61WCLy3liWl_CnOfXWGWEaMX8Vsx8lncjy8PmGg_w09W7tsFZKIubdoLfIhXZ2fBXdjYYl2Z3AiMLVkWnzG_OLUfN8P2rB2TCTH3y_gv3cAuRFXO0Z10h9UUcL56eaG_WUxzLIw2OPKjTxpS5fE', 'Nature', 'heritage', '45,000 CFA', NULL, NULL, '["https://lh3.googleusercontent.com/aida-public/AB6AXuB8CWHRyz19twgOCPSy3p_zWA4nd-D73anO-SCDUh-_Z43r0Mm9fYz0WdjxL7qaRG67n73ZdwMsaQ6EziFmGYOGcSfX6ksFEJNwo-4fwB-eH9Es-cPpSRuu-78lWat9aMrdj5GCjs8VnD-W-W1WcZzOFCdTyKCNCfw5x4H_W-46SlYnlXSNUQGh1X03Uj4aVklxy1KL4qvgm-7K_3XQj9fh1buJCGMW3tvgJpg8TMtg0RHsGGmaUyTzW1isQ1nRSCgM5Qgr5N-GABI"]');

-- Destinations Nearby
INSERT INTO destinations (id, name_en, name_fr, subtitle_en, subtitle_fr, description_en, description_fr, rating, reviews_count, image, category, type, price, distance) VALUES
('local-cuisine', 'Local Cuisine Tour', 'Tour Gastronomique Local', 'Cotonou', 'Cotonou', 'Taste authentic Beninese dishes.', 'Goûtez aux plats béninois authentiques.', 4.5, 89, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIMY-Pp1ZRMJ7H_ZNBAA6yYwFxvx05ML_IdaNQxB9cEb0x3qHl5K_zgL1tA17ix3Y0SN5AgrCRWKOTDnYfcQlJ1A_jpwWWgI-5x-PHn_ReeRc4F8JNLMZbcS-waoFMwROYc31fftDRx7G1K5qJZ5AmUNkNOZwCbdkPe_EhfFlukMDBNJvjU-2KvFLThQL-c3ZySOSnMPx5EE6_--xzQcLbyYVZiQ5c0BuMxv5JRF22k9kopOwfX0XbP1ZvZgHBea0PQE4qjNTgLx8', 'Food', 'nearby', '15,000 CFA', '2.5 km'),

('hotel-du-lac', 'Hotel du Lac', 'Hôtel du Lac', 'Ganvie', 'Ganvié', 'Lakeside luxury accommodation.', 'Hébergement de luxe au bord du lac.', 4.8, 156, 'https://lh3.googleusercontent.com/aida-public/AB6AXuCdNuQ1Ex8GRtResErfS70HehwwNRA5fQ2isNuu3zWb0QuIpMPMjcEXEvfdeZ_zjrmK4inm-6zE3vJpqjIFnpjpDm_kERtk9cPfkNC07JYkiiNa2IGSGehcC-FjLsUJXcG6awkGPaJgrwwxo4roPXUsZDR4fdo4zEZfWcrIWW9sC18TxEH5OeeL7QFVDZmUoDxpyuRfGnpcW1tXkkXrYetwR2rRic3Rt7LF3fuSpud7ZqcnvQfdH8gh5GT5Zl7EoYI-fptQbf_psX8', 'Hotel', 'nearby', '85,000 CFA', '5 km');

-- Tours
INSERT INTO tours (id, name_en, name_fr, description_en, description_fr, duration, stops, price, image, tags, stop_names) VALUES
('slave-route', 'Slave Route Historical Walk', 'Route Historique des Esclaves', 'Walk the historic path in Ouidah, visiting the Museum and the poignant Tree of Forgetfulness.', 'Parcourez le chemin historique à Ouidah, en visitant le musée et l''arbre de l''oubli poignant.', '3 hours', 5, 45, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBAQVYw5fjk0Y2Wb50LuzogsSN2u5aPlQ2_VYcgXxvUYx9uouCzESpSNH4w87SZauSz7Dgv4joD_nzX0NaHUm8mvG9QyjonXhBcrqSwQ83NPo2hTiyYKt2TYDktWwXVkfPh5BZ4BtdT9XcMNiN9J9IqplUmG6VN2Zzn29_bU8XLucPON_ZCn_TFbZT1gnPZrZKb3c4IKz9J56ayotJTu_oKz_Av_pO0uk8Tph8g_TsebZVV7lxh2EbPgYDiCoBU0xZoA1x8dyBkvZ8', '["Heritage"]', '["Ouidah Museum", "Tree of Forgetfulness"]'),

('voodoo-discovery', 'Voodoo Discovery', 'Découverte du Vaudou', 'Explore the spiritual heart of Benin through sacred temples and ceremonies.', 'Explorez le cœur spirituel du Bénin à travers des temples sacrés et des cérémonies.', '5 hours', 4, 75, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQEke-cVK4n7MweCUtc2Z-El6XyaDWC2a_IF4QEauQskyIFQqjUZSxbPvDM06OcSBZDn5sMpPQHtDKe3omv1dVAIT6xtJXsfhzS1yufoQbACkm5Q4SHadi_PVa69QFZ3F0FhKj6rZq7AzRFOIb4Fh4ZjWF330r9UF_ZF3unmn5PIRmH0geXIAUhAri56sq_KXSeJtLH7GNHxEYvoyNNN9TxBUKCmd18d57jcV1YGXqwb9UJpZvtmry-T6Am6Wd3LydaheW4csUvNk', '["Cultural", "Spiritual"]', '["Python Temple", "Sacred Forest"]'),

('pendjari-safari', 'Pendjari Safari', 'Safari Pendjari', 'A 2-day safari adventure in Pendjari National Park with expert guides.', 'Une aventure safari de 2 jours dans le Parc National de la Pendjari avec des guides experts.', '2 Days', 8, 0, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBMjaI-4bdxtZ26wJ1hJQnD7IhGCIBLSuWLQrUhfnW9PFUn-GTf9pYnkIYsZ82hu7CLZ3VxNVkK-lgfPVCnRY-r0Sxcs6YFA6cNG_ysGKbMJsdBmDBqqZArT1Virl3fCRo8VV4rnXhPKDOHOdQZ9gHkfaVe2Ejdb2kEYXP8e6HZ8N2Jq8NyAUoyV8hSaXTQPem_vQTZFvMt7JwKo9nohgoBdj-ev-jxWjKelkKbFjz1seiU4baoU3TTxykocKX6TpqS46K45ftHhsM', '["Nature", "Wildlife"]', '["Pendjari Park", "Tanougou Falls"]');
