-- =============================================
-- GoBénin Seed Data
-- =============================================

-- Destinations Featured
INSERT INTO destinations (id, name_en, name_fr, subtitle_en, subtitle_fr, description_en, description_fr, rating, reviews_count, image, category, type) VALUES
('ouidah', 'Ouidah', 'Ouidah', 'Cultural Capital & History', 'Capitale Culturelle & Histoire', 'Discover the rich history of the Slave Route and the Python Temple.', 'Découvrez la riche histoire de la Route des Esclaves et du Temple des Pythons.', 4.8, 320, 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3BkXgR_L3ed9xOwrgBAV5m2Aitw7Tz0CHUWS05-rlFIBM77fPONvZ1hnSgBe48pjiv2_FTAxWEhv-muGaK70KexZZbW0uvKIrV8ljxJNFS7d3Xjp9FiR50pULWiMWaDp81W6Y7niaOoWUEUvgDGo4HP6eI5Kx3YHos-_ovXU8-qf0Pe8Sierr9ldc6PoDU_1vj4XK_z_RhqpDDNrwfd3w76Eku_UZaHeKxTsr_CJ8t_7UFR1OfFdsYh1yy3Ycplw0KlyelcCdXbQ', 'Heritage', 'featured'),

('grand-popo', 'Grand-Popo', 'Grand-Popo', 'Beach & Relaxation', 'Plage & Détente', 'Serene beaches and colonial architecture.', 'Plages sereines et architecture coloniale.', 4.7, 210, 'https://lh3.googleusercontent.com/aida-public/AB6AXuAg8hSUPvJecRMmZFFQwxj9CjWh2uxxGmTyLDq9xMGao2PEEeLBZsOM8dCVsGKIE7fxWNZou3VUvVA6dqbBO0mG_LFhOBA05AxRYXZBPa0VRDHBCx03RAaTy2nI4OEjFQwKTupmkqSC_ZaHOjz_cL5O88RUKijtxkgsJM8aM6xNSlSDGSvy-Rzb7XkzdnJzNSS7pJ401BL-Hn_Wq8Ms0bHOcptYPBFyItWmGipOj0e6fzm9Vx6JWt6en5XkLiGDxVbEpZX28Tow2J0', 'Relaxation', 'featured'),

('ganvie', 'Ganvie', 'Ganvié', 'The Venice of Africa', 'La Venise de l''Afrique', 'A wonderful lake city at the heart of Benin, a few kilometers from the economic capital, Cotonou. Discover Ganvie, a hidden treasure in West Africa.', 'Merveilleuse ville lacustre située au cœur du Bénin, à quelques kilomètres de la capitale économique, Cotonou. Découvrez Ganvié, un trésor caché au cœur de l''Afrique occidentale.', 4.6, 540, 'https://benintourisme.bj/upload/thumbnails/banners//728410799111001708442794.jpg', 'Culture', 'featured'),

('amazone', 'The Amazone', 'L’Amazone', 'Cotonou', 'Cotonou', 'During a visit to Cotonou, the Amazone is a must-see. This emblematic statue embodies strength, dignity, and resilience, paying tribute to female heroism and Benin''s history.', 'Lors d''une visite à Cotonou, l''Amazone est une étape incontournable. Cette statue emblématique incarne la force, la dignité et la résilience. Elle représente un hommage vibrant à l''héroïsme féminin et à la richesse de l''histoire béninoise.', 4.6, 0, 'https://benintourisme.bj/upload/thumbnails/banners//518600580030001708442568.jpg', 'Culture', 'featured'),

('mur-graffe', 'The Graffiti Wall', 'Le mur graffé', 'Cotonou', 'Cotonou', 'An artistic jewel in the heart of Benin''s capital. Along this colorful wall, creativity bursts with audacity. Here, art meets urban life for an unforgettable visual and cultural experience.', 'Un joyau artistique s''épanouit au cœur de la capitale béninoise. Le long de ce mur coloré, une créativité débordante s''exprime avec audace. Ici, l''art rencontre l''urbanité pour offrir aux passants une expérience visuelle et culturelle inoubliable.', 4.6, 0, 'https://benintourisme.bj/upload/thumbnails/banners//398760049759001708442607.jpg', 'Culture', 'featured'),

('route-des-peches', 'Route des Pêches', 'La route des pêches', 'Atlantic Coast', 'Littoral Atlantique', 'Along the shimmering waters of the Gulf of Guinea stretches a panoramic road dotted with fishing villages and breathtaking coastal scenery.', 'Au bord des eaux scintillantes du golfe de Guinée, s''étend une route panoramique parsemée de villages de pêcheurs pittoresques et de paysages côtiers à couper le souffle : bienvenue sur la Route des Pêches !', 4.6, 0, 'https://benintourisme.bj/upload/thumbnails/banners//271490396816001703041423.jpg', 'Relaxation', 'featured'),

('plage-plm-el-dorado', 'PLM El Dorado Beach', 'Plage PLM El Dorado', 'Cotonou', 'Cotonou', 'On Benin''s Atlantic coast, PLM El Dorado beach in Cotonou is more than a sandy shore: a haven for relaxation and entertainment.', 'Située sur la côte atlantique du Bénin, la plage PLM El Dorado à Cotonou est bien plus qu''un simple littoral de sable : c''est un havre de paix et de divertissement où les visiteurs peuvent se détendre, se ressourcer et se divertir.', 4.6, 0, 'https://benintourisme.bj/upload/thumbnails/banners//795340395530001708442687.jpg', 'Relaxation', 'featured'),

('babs-dock', 'Bab''s Dock', 'Bab''s Dock', 'Ganvie', 'Ganvié', 'A scenic lagoon-side stop where the setting and wildlife make for a memorable visit.', 'Sur place le cadre est magique, la lagune, les animaux (ânes, tortues, alligators, singes) raviront les enfants.', 4.3, 94, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/a1/c4/b1/tramonto-a-bob-s-dock.jpg?h=-1&s=1&w=500', 'Relaxation', 'featured'),

('marche-dantokpa', 'Marché Dantokpa', 'Marché Dantokpa', 'Cotonou', 'Cotonou', 'A sprawling market where you can find nearly anything and get lost in lively alleys.', 'Quelque soit le produit recherché, il se trouve à Dantokpa. Quel plaisir de se perdre dans les allées de ce marché.', 4.0, 63, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/73/38/2b/marche-dantokpa.jpg?h=400&s=1&w=500', 'Culture', 'featured'),

('porte-du-non-retour', 'Door of No Return', 'La Porte du Non Retour', 'Ouidah', 'Ouidah', 'A poignant memorial site often visited with guides for historical context.', 'Visite plus qu''émouvante pour qui bénéficiera de la présence et des explications d''un guide.', 4.1, 67, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/62/d2/47/ouidah-s-non-retour-gate.jpg?h=-1&s=1&w=500', 'Heritage', 'featured'),

('lac-nokoue', 'Lake Nokoué', 'Lac Nokoué', 'Near Ganvie', 'Près de Ganvié', 'A lake best known for excursions to the stilt city of Ganvié.', 'Le lac de Nokoue est surtout intéressant pour la visite de la cité lacustre de Ganvié, avec ses maisons sur pilotis.', 4.4, 32, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/16/35/2d/lac-nokoue.jpg?h=400&s=1&w=500', 'Nature', 'featured'),

('temple-des-pythons', 'Python Temple', 'Temple des Pythons', 'Ouidah', 'Ouidah', 'A Vodoun worship site where pythons are revered and protected.', 'Lieu de culte Vodoun où le serpent python est toujours adoré et protégé.', 3.6, 27, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/9b/a0/f8/img-20190220-123547013.jpg?h=-1&s=1&w=500', 'Culture', 'featured'),

('fidjrosse-beach', 'Fidjrosse Beach', 'Plage de Fidjrossè', 'Cotonou', 'Cotonou', 'A coastal stretch popular for walks along the seaside road toward Ouidah.', 'Belle promenade sur la nouvelle route et sur la côte en direction d''Ouidah.', 3.6, 25, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/57/1b/12/amoureux-de-la-nature.jpg?h=400&s=1&w=500', 'Relaxation', 'featured'),

('artisanal-center', 'Artisanal Center', 'Artisanal Center', 'Cotonou', 'Cotonou', 'A crafts hub with bronze work and artisanal pieces, including older items.', 'Il y a de très belles pièces, parfois anciennes, y compris en bronze.', 3.8, 25, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/28/93/b5/ce/artisanal-center.jpg?h=400&s=1&w=500', 'Culture', 'featured'),

('grande-mosquee-porto-novo', 'Great Mosque of Porto-Novo', 'La grande mosquée de Porto-Novo', 'Porto-Novo', 'Porto-Novo', 'A landmark religious site in Benin’s administrative capital.', 'Porto-Novo est la capitale administrative du Bénin; sa grande mosquée est un site religieux majeur.', 4.0, 22, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/aa/54/89/mosque.jpg?h=-1&s=1&w=500', 'Heritage', 'featured'),

('palais-rois-abomey', 'Royal Palaces of Abomey', 'Palais des rois d''Abomey', 'Abomey', 'Abomey', 'Historic royal palaces that trace the legacy of the Kingdom of Dahomey.', 'Les palais royaux d''Abomey retracent l''histoire du Royaume du Dahomey.', 3.7, 12, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/73/28/7d/royal-palaces-of-abomey.jpg?h=400&s=1&w=500', 'Heritage', 'featured'),

('musee-zinsou', 'Zinsou Foundation Museum', 'Musée de la Fondation Zinsou', 'Ouidah', 'Ouidah', 'A museum showcasing remarkable art exhibitions in Ouidah.', 'Le musée de la Fondation Zinsou à Ouidah offre des expositions d''art remarquables.', 4.5, 9, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/20/01/48/3c/le-batiment-du-musee.jpg?h=-1&s=1&w=500', 'Culture', 'featured');

-- Destinations Heritage
INSERT INTO destinations (id, name_en, name_fr, subtitle_en, subtitle_fr, description_en, description_fr, rating, reviews_count, image, category, type, price, hours, duration, images) VALUES
('royal-palaces', 'Royal Palaces', 'Palais Royaux', 'Abomey', 'Abomey', 'The Royal Palaces of Abomey are the major material testimony to the Kingdom of Dahomey which developed from the mid-17th century. Founded in 1625 by the Fon people, the kingdom became a powerful military and commercial empire.', 'Les Palais Royaux d''Abomey sont le principal témoignage matériel du Royaume du Dahomey qui s''est développé à partir du milieu du XVIIe siècle. Fondé en 1625 par le peuple Fon, le royaume est devenu un puissant empire militaire et commercial.', 4.8, 124, 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgFVzBhtc_W5MfJulzowEjdsYqH8v0L61XtoHTWxrV67Bej4KjrCF1QveYTup1Dut8rJzJgcwBhIrrmS60owscvkdPx5K38PeRLSHlJ3dximT3rfwkrSL9vM8NytlK0fEVFecpVkuRDEGrewmZR0Fn4PoaZ6kcvQ6Pu4e9iXanUV1HGnHanMvnAoZrWcC2pCC2eSr3ed1twnmuLriRp51SLMp3Vhq2kKst61x36siZMYOFCDf0O1Yn199MzNIVTD2LVTUJ4vDXP6Y', 'Heritage', 'heritage', '2,500 CFA', '09:00 - 18:00', '2 - 3 Hrs', '["https://lh3.googleusercontent.com/aida-public/AB6AXuC2mw7lkILzKgHvVUKG37_4IfsDR4UGxuPIYYWfnZy_lEmrnN73hT4eHmLPFUibU63jovzesMrG1rc78mb5P8l3V1bbXEhrr_qJCxzUp4pkzzZKGYkKv7VpHAU5Z3tAmUFL7JrMl8QjKXPpsFBXndCQDRR_g1mOtmQDHNQh3YrdBc2Aub1IHtc-su5NesHs_ZkDorBkMUY4rYfCH4iTRcH3-RnKxAIOA9Pxoop98IdV_SBDGBROvk375BTllzdQp0nepethef7MfHU"]'),

('pendjari', 'Pendjari National Park', 'Parc de la Pendjari', 'Atacora', 'Atacora', 'With spectacular landscapes, abundant wildlife, and endless adventure opportunities, this national park is a top destination for nature lovers and travelers.', 'Avec ses paysages spectaculaires, sa faune sauvage abondante et ses opportunités d''aventure sans fin, ce parc national est une destination de choix pour les amoureux de la nature et les passionnés de voyage.', 4.9, 89, 'https://benintourisme.bj/upload/thumbnails/banners//834760438538001728494098.jpg', 'Nature', 'heritage', NULL, NULL, NULL, '[]'),

('route-des-tata', 'Route des Tata', 'La route des Tata', 'Atacora', 'Atacora', 'In the heart of Atacora, the Route des Tata and Koutammakou reveal themselves as unique treasures of Benin, listed as UNESCO World Heritage—places where history and culture meet a spectacular landscape.', 'Au cœur de l''Atacora, la Route des Tata et le Koutammakou se dévoilent comme des trésors uniques du Bénin, inscrits au patrimoine mondial de l''UNESCO. Lieux où l''histoire et la culture se rencontrent dans un paysage spectaculaire.', 0, 0, 'https://benintourisme.bj/upload/thumbnails/banners//524600414734001716379105.jpg', 'Heritage', 'heritage', NULL, NULL, NULL, '[]'),

('w-national-park', 'W National Park', 'Parc national du W', 'Alibori', 'Alibori', 'A protected area in northern Benin, part of the transboundary W-Arly-Pendjari complex.', 'Aire protégée du nord du Bénin, faisant partie du complexe transfrontalier W-Arly-Pendjari.', 0, 0, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Mekrou_river_in_W-National_Park_MS_6380.JPG/330px-Mekrou_river_in_W-National_Park_MS_6380.JPG', 'Nature', 'heritage', NULL, NULL, NULL, '[]'),

('koutammakou', 'Koutammakou (Batammariba)', 'Koutammakou (Batammariba)', 'Atacora', 'Atacora', 'A living cultural landscape known for Batammariba earthen tower-houses (takienta), listed as UNESCO World Heritage.', 'Paysage culturel vivant des Batammariba, connu pour les maisons-tours en terre (takienta), classé au patrimoine mondial de l''UNESCO.', 0, 0, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Togo_Taberma_house_02.jpg/330px-Togo_Taberma_house_02.jpg', 'Heritage', 'heritage', NULL, NULL, NULL, '[]'),

('tanougou-falls', 'Tanougou Falls', 'Chutes de Tanougou', 'Atacora (Tanguiéta)', 'Atacora (Tanguiéta)', 'Waterfalls near the village of Tanougou in the Atacora, a popular nature stop near Pendjari.', 'Chutes d''eau situées près du village de Tanougou, dans l''Atacora, une halte nature appréciée proche de la Pendjari.', 0, 0, 'https://upload.wikimedia.org/wikipedia/commons/3/32/Chutes_de_Tanougou_%283%29.jpg', 'Nature', 'heritage', NULL, NULL, NULL, '[]');

-- Destinations Nearby
INSERT INTO destinations (id, name_en, name_fr, subtitle_en, subtitle_fr, description_en, description_fr, rating, reviews_count, image, category, type, price, distance) VALUES
('local-cuisine', 'Local Cuisine Tour', 'Tour Gastronomique Local', 'Cotonou', 'Cotonou', 'Taste authentic Beninese dishes.', 'Goûtez aux plats béninois authentiques.', 4.5, 89, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIMY-Pp1ZRMJ7H_ZNBAA6yYwFxvx05ML_IdaNQxB9cEb0x3qHl5K_zgL1tA17ix3Y0SN5AgrCRWKOTDnYfcQlJ1A_jpwWWgI-5x-PHn_ReeRc4F8JNLMZbcS-waoFMwROYc31fftDRx7G1K5qJZ5AmUNkNOZwCbdkPe_EhfFlukMDBNJvjU-2KvFLThQL-c3ZySOSnMPx5EE6_--xzQcLbyYVZiQ5c0BuMxv5JRF22k9kopOwfX0XbP1ZvZgHBea0PQE4qjNTgLx8', 'Food', 'nearby', '15,000 CFA', '2.5 km'),

('hotel-du-lac', 'Hotel du Lac', 'Hôtel du Lac', 'Ganvie', 'Ganvié', 'Lakeside luxury accommodation.', 'Hébergement de luxe au bord du lac.', 4.8, 156, 'https://lh3.googleusercontent.com/aida-public/AB6AXuCdNuQ1Ex8GRtResErfS70HehwwNRA5fQ2isNuu3zWb0QuIpMPMjcEXEvfdeZ_zjrmK4inm-6zE3vJpqjIFnpjpDm_kERtk9cPfkNC07JYkiiNa2IGSGehcC-FjLsUJXcG6awkGPaJgrwwxo4roPXUsZDR4fdo4zEZfWcrIWW9sC18TxEH5OeeL7QFVDZmUoDxpyuRfGnpcW1tXkkXrYetwR2rRic3Rt7LF3fuSpud7ZqcnvQfdH8gh5GT5Zl7EoYI-fptQbf_psX8', 'Hotel', 'nearby', '85,000 CFA', '5 km');

-- Tours
INSERT INTO tours (id, name_en, name_fr, description_en, description_fr, duration, stops, price, image, tags, stop_names) VALUES
('slave-route', 'Slave Route Historical Walk', 'Route Historique des Esclaves', 'Walk the historic path in Ouidah, visiting the Museum and the poignant Tree of Forgetfulness.', 'Parcourez le chemin historique à Ouidah, en visitant le musée et l''arbre de l''oubli poignant.', '3 hours', 5, 45, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBAQVYw5fjk0Y2Wb50LuzogsSN2u5aPlQ2_VYcgXxvUYx9uouCzESpSNH4w87SZauSz7Dgv4joD_nzX0NaHUm8mvG9QyjonXhBcrqSwQ83NPo2hTiyYKt2TYDktWwXVkfPh5BZ4BtdT9XcMNiN9J9IqplUmG6VN2Zzn29_bU8XLucPON_ZCn_TFbZT1gnPZrZKb3c4IKz9J56ayotJTu_oKz_Av_pO0uk8Tph8g_TsebZVV7lxh2EbPgYDiCoBU0xZoA1x8dyBkvZ8', '["Heritage"]', '["Ouidah Museum", "Tree of Forgetfulness"]'),

('voodoo-discovery', 'Voodoo Discovery', 'Découverte du Vaudou', 'Explore the spiritual heart of Benin through sacred temples and ceremonies.', 'Explorez le cœur spirituel du Bénin à travers des temples sacrés et des cérémonies.', '5 hours', 4, 75, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDQEke-cVK4n7MweCUtc2Z-El6XyaDWC2a_IF4QEauQskyIFQqjUZSxbPvDM06OcSBZDn5sMpPQHtDKe3omv1dVAIT6xtJXsfhzS1yufoQbACkm5Q4SHadi_PVa69QFZ3F0FhKj6rZq7AzRFOIb4Fh4ZjWF330r9UF_ZF3unmn5PIRmH0geXIAUhAri56sq_KXSeJtLH7GNHxEYvoyNNN9TxBUKCmd18d57jcV1YGXqwb9UJpZvtmry-T6Am6Wd3LydaheW4csUvNk', '["Cultural", "Spiritual"]', '["Python Temple", "Sacred Forest"]'),

('pendjari-safari', 'Pendjari Safari', 'Safari Pendjari', 'A 2-day safari adventure in Pendjari National Park with expert guides.', 'Une aventure safari de 2 jours dans le Parc National de la Pendjari avec des guides experts.', '2 Days', 8, 0, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBMjaI-4bdxtZ26wJ1hJQnD7IhGCIBLSuWLQrUhfnW9PFUn-GTf9pYnkIYsZ82hu7CLZ3VxNVkK-lgfPVCnRY-r0Sxcs6YFA6cNG_ysGKbMJsdBmDBqqZArT1Virl3fCRo8VV4rnXhPKDOHOdQZ9gHkfaVe2Ejdb2kEYXP8e6HZ8N2Jq8NyAUoyV8hSaXTQPem_vQTZFvMt7JwKo9nohgoBdj-ev-jxWjKelkKbFjz1seiU4baoU3TTxykocKX6TpqS46K45ftHhsM', '["Nature", "Wildlife"]', '["Pendjari Park", "Tanougou Falls"]');
